prefix = "miao"

[etcd]
hosts = ["miao-etcd:2379"]
key = "gateway"

[mysql]
key = ""

username = "miao"
password = "123456"
address = "miao-mysql-master:3306"
database = "miao"
other = "?charset=utf8&parseTime=True&loc=Local"

dsn = ""

[mysql-slave]
key = ""

username = "miao"
password = "123456"
address = "miao-mysql-slave:3306"
database = "miao"
other = "?charset=utf8&parseTime=True&loc=Local"

dsn = ""

