prefix = "miao"

[grpc]
name = "pet"
listenOn = "127.0.0.1:8081"

[http]
listenOn = "127.0.0.1:8080"

[etcd]
hosts = ["miao-etcd:2379"]
key = "pet"

[mysql]
# etcd 默认mysql
key = "mysql-master"

# 自定义
username = ""
password = ""
address = ""
database = ""
other = ""

dsn = ""

[traefik]
provider = "etcd"